#!/usr/bin/env bash

set -eu

# Install Homebrew if needed
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Install packages
if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating Homebrew bundle"
  brew bundle --all --cleanup --global --quiet
fi
