#!/usr/bin/env bash

# Derived from https://mths.be/macos

set -e

# Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Dock                                                                        #
###############################################################################

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Set auto-hide speed
defaults write com.apple.dock autohide-time-modifier -float 0.2

# Do not show recent applications
defaults write com.apple.dock show-recents -bool false

# Restart Dock
killall Dock


###############################################################################
# Trackpad                                                                    #
###############################################################################

# Map bottom right corner to right-click
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
# defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
# defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

###############################################################################
# Conclusion                                                                  #
###############################################################################
echo "Done. Note that some of these changes require a logout/restart to take effect."