#!/usr/bin/env bash

set -eu

# Inspired by https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
# sudo -v

# Keep-alive: update existing `sudo` time stamp until this script has finished
# while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Keyboard Shortcuts                                                          #
###############################################################################

# Disable Show Spotlight search keyboard shortcut so that ⌘-Space can be used with the application launcher
defaults write com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add 64 "<dict><key>enabled</key><false/></dict>"

# Force keyboard shortcuts reload
/System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u


###############################################################################
# Dock                                                                        #
###############################################################################

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -int 1

# Set auto-hide speed
defaults write com.apple.dock autohide-time-modifier -float 0.2

# Do not show recent applications
defaults write com.apple.dock show-recents -bool false

# Set Dock icon size
defaults write com.apple.dock tilesize -int 76

# Restart Dock
killall Dock


###############################################################################
# Conclusion                                                                  #
###############################################################################
# echo "Done. Note that some of these changes require a logout/restart to take effect."