- name: Enable Menu Bar Transparency
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleEnableMenuBarTransparency
    type: bool
    value: true
    state: present

- name: Use Dark Menu Bar and Dock
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark
    state: present

- name: Double-click a Window's Title Bar to Zoom
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleActionOnDoubleClick
    type: string
    value: Maximize
    state: present

- name: Enable Mouse Right-click
  osx_defaults:
    domain: com.apple.AppleMultitouchMouse
    key: MouseButtonMode
    type: string
    value: TwoButton
    state: present

- name: Increase Mouse Speed
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.scaling
    type: float
    value: 1.5
    state: present

- name: Disable "Look up & data detectors" Trackpad Gesture
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerTapGesture
    type: int
    value: 0
    state: present

- name: Enable Right-click in the Trackpad Lower Right Corner
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
    state: present

- name: Enable Trackpad Haptic Feedback
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.forceClick
    type: int
    value: 1
    state: present

- name: Set Cursor Speed When Using Trackpad
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: int
    value: 1
    state: present

- name: Restart the Finder to Pick Up New Settings
  command: killall Finder

- name: Restart SystemUIServer to Pick Up New Settings
  command: killall SystemUIServer
