- name: Install Homebrew packages
  homebrew:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_packages }}'

- name: Tap into caskroom/cask
  homebrew_tap:
    tap: caskroom/cask
    state: present
  # KLUDGE: Ansible has a bug where taps succeed but look like a failure
  # https://github.com/ansible/ansible/issues/40853
  ignore_errors: yes

- name: Tap into caskroom/fonts
  homebrew_tap:
    tap: caskroom/fonts
    state: present
  # KLUDGE: Ansible has a bug where taps succeed but look like a failure
  # https://github.com/ansible/ansible/issues/40853
  ignore_errors: yes

- name: Install Homebrew casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
    install_options: appdir=/Applications
  with_items: '{{ homebrew_casks }}'

- name: Ensures ZSH configuration directory exists
  file:
    path: ~/.zsh
    state: directory

- name: Copy initialization file
  copy:
    src: '{{ role_path }}/files/homebrew_init.zsh'
    dest: ~/.zsh/homebrew_init.zsh

- name: Copy update file
  copy:
    src: '{{ role_path }}/files/homebrew_update.zsh'
    dest: ~/.zsh/homebrew_update.zsh
