# Brew Formulas
tap 'homebrew/dupes'
brew 'awscli'
brew 'diff-so-fancy'
brew 'direnv'
brew 'dockutil'
brew 'git'
brew 'git-extras'
brew 'git-secrets'
brew 'go'
brew 'graphviz'
brew 'gzip'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'make'
brew 'mas'
brew 'nvm'
brew 'openssh'
brew 'openssl'
brew 'pv'
brew 'terraform'
brew 'wget', args: ['enable-iri']
brew 'zsh'

# Brew GNU Formulas
brew 'coreutils'
brew 'findutils', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'grep', args: ['with-default-names']

# Cask Applications
cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'
cask '1password'
cask 'alfred'
cask 'archiver'
cask 'bartender'
cask 'caffeine'
cask 'charles'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'fantastical'
cask 'firefox'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'kaleidoscope'
cask 'mplayer-osx-extended'
cask 'path-finder'
cask 'sequel-pro'
cask 'skitch'
cask 'skype'
cask 'tower'
cask 'transmit'
cask 'typora'
cask 'visual-studio-code'

# Cask Fonts
tap 'caskroom/fonts'
cask 'font-inconsolata-dz-for-powerline'
