# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
tap homebrew/dupes
install homebrew/dupes/grep

# Install latest PHP version
tap josegonzalez/homebrew-php
install php55
link php55
install php55-intl
install php55-xdebug

# Install various core utilities
install htop-osx
install tree

# Install sitespeed.io
tap sitespeedio/sitespeedio
tap tobli/browsertime
install sitespeed.io

# Install various formulae
install composer
install git
install graphviz
install ngrep
install node
install mtr
install qcachegrind
install tcpdump

# Remove outdated versions from the cellar
cleanup
