- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present
    install_options: appdir=/Applications

- name: Install Visual Studio Code extensions
  command: code --install-extension {{item}}
  with_items: '{{ extensions }}'

- name: Copy configuration file
  copy:
    src: '{{ role_path }}/files/settings.json'
    dest: ~/Library/Application Support/Code/User/settings.json

- name: Copy initialization file
  copy:
    src: '{{ role_path }}/files/visual-studio-code_init.zsh'
    dest: ~/.zsh/visual-studio-code_init.zsh
